eureka:
  client:
    healthcheck:
      enabled: true
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
spring:
  application:
    name: feign-hystrix-consumer
server:
  port: 9002
feign:
  hystrix:
    enabled: true
